language: crystal
crystal:
  - latest
  - nightly
services:
  - postgresql
script:
  - crystal spec
  - crystal tool format spec src --check
cache:
  directories:
    - bin/lucky
    - lib
    - .shards
